### PR TITLE
test: Add missing unit tests for controller server and utils

### LINKED ISSUE #121: improve unit test coverage
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

unit test coverage is now 72%:

https://coveralls.io/github/kubernetes-csi/csi-driver-nfs

image

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by dr0pdb**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR adds some of the missing unit tests for the controller server and utils in `pkg/nfs`

**Which issue(s) this PR fixes**:

Fixes #121 

**Special notes for your reviewer**:
none

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Comment by dr0pdb** [comment]
This is in the draft state since I am still working on the Delete volume unit test. I'll mark it ready afterward.

**Comment by dr0pdb** [comment]
@andyzhangx This is ready for review.

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
