### PR TITLE
release tools

### PR DESCRIPTION
**Pull request by pohly**
This imports the shared csi-release-tools and uses it for Travis CI
and building. The binary and image name are "nfsplugin", as before.

/assign @msau42

### CODE REVIEW

**Comment by pohly** [comment]
Travis CI still needs to be activated for this repo. This can only be done by someone in the kubernetes-csi admin group.

Once this PR is merged, we should get a "canary" image for the master branch build that gets triggered by merging.

**Comment by msau42** [comment]
I enabled travis. We'll see on the next pull if it works. I tried to manually trigger a build, but it was still skipping the image pushing part for some reason

**Comment by pohly** [comment]
PR builds don't push images. We don't want them to overwrite any of the other images, and generating one image per PR would probably be too much garbage.

https://travis-ci.org/kubernetes-csi/csi-driver-nfs/builds/497214712 shows that a master branch build tried to push quay.io/k8scsi/nfsplugin:canary, but that failed:
```
The push refers to a repository [quay.io/k8scsi/nfsplugin]
11a0c6611026: Preparing
cbfe4a19a23e: Preparing
129b697f70e9: Preparing
unauthorized: access to the requested resource is not authorized
make: *** [push-nfsplugin] Error 1
Done. Your build exited with 0.
```

Do we want TravisCI to report job success despite the failure to push the image? This has always been this way, because pushing is done in an `after_success` operation which by definition runs after a job has been determined to be successful and thus (my interpretation) will not change job success, so I suppose it is intentional?

If we wanted pushing to be part of the job, it would have to be part of the build script.

**Comment by msau42** [comment]
Sorry I don't mean PR builds should push images, I meant that the job I triggered off of the master branch didn't push.  Let me investigate the authorization error.

**Comment by pohly** [comment]
Michelle Au <notifications@github.com> writes:
> Sorry I don't mean PR builds should push images

So we agree :-) I just mentioned it because it could have been one
reason why nothing was pushed.

**Pull request merged**
