### PR TITLE
CI: enable golint

### LINKED ISSUE #90: CI: Enable go linter in GH Actions
Enable go linter as a GH Actions workflow under `static.yaml` (Similar to - https://github.com/kubernetes-csi/csi-driver-smb/blob/master/.github/workflows/static.yaml). However, the check will still fail as the code in this repository has many linting errors which need to be fixed.

### PR DESCRIPTION
**Pull request by mayankshah1607**
Signed-off-by: Mayank Shah <mayankshah1614@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #90

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve
could you also add this check to SMB driver? thanks.

**Comment by andyzhangx** [comment]
maybe you could help? @dr0pdb thanks.

**Comment by mayankshah1607** [comment]
@andyzhangx SMB driver already has this check running - https://github.com/kubernetes-csi/csi-driver-smb/blob/master/.github/workflows/static.yaml

**Comment by andyzhangx** [comment]
> maybe you could help? @dr0pdb thanks.

not needed any more.

**Pull request merged**
