### PR TITLE
add subPath e2e test

### LINKED ISSUE #162: add subPath e2e test
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by boddumanohar**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
add subPath e2e test

**Which issue(s) this PR fixes**:
Fixes #162 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Review by andyzhangx — COMMENTED** [review]
/ok-to-test

**Comment by msau42** [comment]
@andyzhangx instead of writing custom tests, can we reuse the kubernetes e2e testsuites? You get 50+ test cases for free. https://github.com/kubernetes/kubernetes/tree/fa558043c02cae10ffbe001b46a7166231d07f60/test/e2e/storage/external

**Comment by andyzhangx** [comment]
> @andyzhangx instead of writing custom tests, can we reuse the kubernetes e2e testsuites? You get 50+ test cases for free. https://github.com/kubernetes/kubernetes/tree/fa558043c02cae10ffbe001b46a7166231d07f60/test/e2e/storage/external

thanks for reminder, since this case is already done, let's merge it first.
I have a plan to reuse the kubernetes e2e testsuites in this project, will work on that later.

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
