### PR TITLE
Add Helm chart for CSI NFS driver

### PR DESCRIPTION
**Pull request by mayankshah1607**
Signed-off-by: Mayank Shah <mayankshah1614@gmail.com>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add Helm chart for CSI NFS driver

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by msau42** [comment]
How do we keep the manifests in sync between the helm chart and deploy folder

**Comment by andyzhangx** [comment]
> How do we keep the manifests in sync between the helm chart and deploy folder

good question, we could partially keep sync between these two folders, see example here: https://github.com/kubernetes-csi/csi-driver-smb/blob/master/hack/verify-helm-chart.sh, @mayankshah1607 would you work on that later? thanks.

**Comment by mayankshah1607** [comment]
> good question, we could partially keep sync between these two folders, see example here: https://github.com/kubernetes-csi/csi-driver-smb/blob/master/hack/verify-helm-chart.sh, @mayankshah1607 would you work on that later? thanks.\

Sure. Maybe we could add a separate workflow for static checks that verifies linting, etc. along with the helm chart sync.

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
