### PR TITLE
fix: use `mkdir -p` for creating subdir in mounted base-dir

### LINKED ISSUE #411: `mkdir /tmp/pvc-bla/<subDir>: no such file or directory` when `subDir` is used
**What happened**:
When `subDir` parameter is in use in declaring the [storage class](https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/docs/driver-parameters.md#storage-class-usage-dynamic-provisioning), the PVC would result in a mkdir error.

**What you expected to happen**:
`mkdir -p` should be used instead to support `subDir`

**How to reproduce it**:
pass a `subDir` parameter in storage class

**Anything else we need to know?**:
Nah

**Environment**:

- CSI Driver version: registry.k8s.io/sig-storage/csi-provisioner:v3.2.0
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8+k3s1"
- OS (e.g. from /etc/os-release): Ubuntu 20.04.5 LTS
- Kernel (e.g. `uname -a`): Linux <hostname> 5.15.0-58-generic # 64 ~20.04.1-Ubuntu SMP Fri Jan 6 16:42:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by alankan-finocomp**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

 /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
It creates also parent directories of sub-directories under the mounted base-dir. Just like `mkdir -p` does.

**Which issue(s) this PR fixes**:

Fixes #411

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Review by andyzhangx — COMMENTED** [review]
/ok-to-test

**Comment by alankan-finocomp** [comment]
Sorry I am new to this prow tool and a bit lost about which line of the e2e-tests failed at :( Could you help me understand it?

**Comment by andyzhangx** [comment]
the test error would be fixed by https://github.com/kubernetes-csi/csi-driver-nfs/pull/409

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by alankan-finocomp** [comment]
@andyzhangx Thank you very much for reviewing and merging this PR promptly :bow: 

May I ask if there is any upcoming release including this change please?

**Pull request merged**
