### PR TITLE
Add more access modes to volume capabilities

### PR DESCRIPTION
**Pull request by msau42**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
By supporting MULTI_NODE_MULTI_WRITER, we inherently support all the other access modes.  Also store supported access modes as a map to make it easier to lookup.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Adds support all access modes.
```

### CODE REVIEW

**Comment by msau42** [comment]
cc @tombarron @wozniakjan

**Comment by tombarron** [comment]
Looks good to me, thanks!  I hadn't noticed that the other modes weren't explicitly included in the volume capabilities.

**Comment by tombarron** [comment]
/lgtm
/approve
just for the record :D

**Comment by msau42** [comment]
@tombarron, @wozniakjan I suggest requesting membership to kubernetes-csi by opening an issue in kubernetes/org. And then we can add you as reviewers for this repo :-)

**Comment by wozniakjan** [comment]
/approve
/lgtm

trying as freshly added member, suspect I may still need some additional powers here

**Pull request merged**
