### PR TITLE
Update base image to `k8s.gcr.io/build-image/debian-base-amd64:v2.1.3`

### PR DESCRIPTION
**Pull request by mayankshah1607**
Signed-off-by: Mayank Shah <mayankshah1614@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Update base image to `k8s.gcr.io/build-image/debian-base-amd64:v2.1.3`

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
same `nfs-common` package install issue here:
```
Setting up nfs-common (1:1.3.4-2.5+deb10u1) ...
/var/lib/dpkg/info/nfs-common.postinst: 7: /var/lib/dpkg/info/nfs-common.postinst: ucf: not found
dpkg: error processing package nfs-common (--configure):
 installed nfs-common package post-installation script subprocess returned error exit status 127
Processing triggers for libc-bin (2.28-10) ...
Errors were encountered while processing:
 nfs-common
[91mE: Sub-process /usr/bin/dpkg returned an error code (1)
[0mThe command '/bin/sh -c apt update && apt install -y nfs-common jq' returned a non-zero code: 100
```

**Comment by mayankshah1607** [comment]
@andyzhangx I'm suspecting there's something wrong with the  `k8s.gcr.io/build-image/debian-base-amd64:v2.1.3`
The driver will not work if `nfs-common` is not installed, hence the test cases are failing. Will have to investigate a bit deeper into the base image configuration

**Comment by andyzhangx** [comment]
> @andyzhangx I'm suspecting there's something wrong with the `k8s.gcr.io/build-image/debian-base-amd64:v2.1.3`
> The driver will not work if `nfs-common` is not installed, hence the test cases are failing. Will have to investigate a bit deeper into the base image configuration

`nfs-common` must be installed, current issue is there is installation error in installing `nfs-common` process

**Comment by mayankshah1607** [comment]
> nfs-common must be installed, current issue is there is installation error in installing nfs-common process

I think there is an issue in the base image configuration that is causing this error. I will verify

**Comment by andyzhangx** [comment]
any progress made? @mayankshah1607

**Comment by andyzhangx** [comment]
any update? @mayankshah1607
Are you able to hep? @dr0pdb thanks

**Comment by andyzhangx** [comment]
related to this issue: https://github.com/kubernetes-sigs/blob-csi-driver/issues/220

**Comment by mayankshah1607** [comment]
> any update? @mayankshah1607

Nope, not yet. Tried a couple of things, but I would appreciate any help here, thanks

**Comment by mayankshah1607** [comment]
@andyzhangx Can we use `ubuntu:20.10` as base image instead? I'm not entirely sure about what may be misconfigured in the debian base image

**Comment by mayankshah1607** [comment]
Closing this as it is not being currently worked on.

**Pull request closed without merging**
