### PR TITLE
fix: change the way to install CSC to fix integration test

### PR DESCRIPTION
**Pull request by songjiaxun**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

/kind failing-test

**What this PR does / why we need it**:

Change the way to install CSC to avoid integration test failures.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by songjiaxun** [comment]
The integration test occasionally fails at the following step, not deterministic. Troubleshooting here.
```
Delete volume test:
I1119 05:29:35.627334    4902 utils.go:63] GRPC call: /csi.v1.Controller/DeleteVolume
I1119 05:29:35.627366    4902 utils.go:64] GRPC request: {"volume_id":"127.0.0.1//citest-1605763749"}
I1119 05:29:35.627446    4902 controllerserver.go:242] internally mounting 127.0.0.1:/ at /tmp/citest-1605763749
I1119 05:29:35.667888    4902 controllerserver.go:131] Removing subdirectory at /tmp/citest-1605763749/citest-1605763749
context deadline exceeded
```

**Comment by songjiaxun** [comment]
d

> The integration test occasionally fails at the following step, not deterministic. Troubleshooting here.
> 
> ```
> Delete volume test:
> I1119 05:29:35.627334    4902 utils.go:63] GRPC call: /csi.v1.Controller/DeleteVolume
> I1119 05:29:35.627366    4902 utils.go:64] GRPC request: {"volume_id":"127.0.0.1//citest-1605763749"}
> I1119 05:29:35.627446    4902 controllerserver.go:242] internally mounting 127.0.0.1:/ at /tmp/citest-1605763749
> I1119 05:29:35.667888    4902 controllerserver.go:131] Removing subdirectory at /tmp/citest-1605763749/citest-1605763749
> context deadline exceeded
> ```

@andyzhangx  Could you help me with this error? I checked everything I could, but the integration test just fails at the last step "delete volume". It fails occasionally on Azure Stack as well. I compare the logs with the sanity test, everything looks good to me. Just could not figure out why it fails with the error `context deadline exceeded`.

**Comment by mayankshah1607** [comment]
@songjiaxun Can we try using the `--timeout` flag with `csc` and increase the duration to `10m`? It could be that the default `1m` is too less

**Comment by songjiaxun** [comment]
> @songjiaxun Can we try using the `--timeout` flag with `csc` and increase the duration to `10m`? It could be that the default `1m` is too less

Increasing the timeout duration helps! Thank you! Although it's a bit strange that it takes so long (more than 1 min) to just delete a subdirectory.

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
