### PR TITLE
Update k8s.io/kubernetes to use v1.18.0

### PR DESCRIPTION
**Pull request by mayankshah1607**
Signed-off-by: Mayank Shah <mayankshah1614@gmail.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Use `update-gomod.sh` to update the dependencies to use k8s.io/kubernetes v1.18.0

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
are you going to fix this or is it necessary for this upgrade?

**Comment by mayankshah1607** [comment]
@andyzhangx to migrate the E2E test from smb driver, we need to use the test `framework` package from `k8s.io/kubernetes v1.18.0`
Currently we're using v1.14, so I've updated the dependences and vendor

**Review by andyzhangx — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
