### PR TITLE
CI: Add static checks in GH Actions

### PR DESCRIPTION
**Pull request by mayankshah1607**
Signed-off-by: Mayank Shah <mayankshah1614@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
- Add static checks in GH Actions
- Fix `hack/verify-helm-chart.sh` error

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
e2e test is broken due to credential issue now

**Comment by mayankshah1607** [comment]
> 2020/11/16 06:39:46 process.go:153: Running: bash -c . hack/lib/version.sh && KUBE_ROOT=. kube::version::get_version_vars && echo "${KUBE_GIT_VERSION-}"
2020/11/16 06:39:46 process.go:155: Step 'bash -c . hack/lib/version.sh && KUBE_ROOT=. kube::version::get_version_vars && echo "${KUBE_GIT_VERSION-}"' finished in 269.211761ms
2020/11/16 06:39:46 main.go:316: Something went wrong: error creating deployer: failed Docker login with error: exit status 1

@andyzhangx e2e job seems to be failing with a strange error. Any idea why this may be happening?

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
