### PR TITLE
fix: helm lint

### PR DESCRIPTION
**Pull request by oreissig**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
We have helm lint running as part of our deployment pipeline. The provided helm chart does not pass this validation without forking and local adjustments, which I'd like to avoid.
```
helm lint charts/latest/csi-driver-nfs
==> Linting charts/latest/csi-driver-nfs
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/rbac-csi-nfs.yaml: unable to parse YAML: invalid Yaml document separator: kind: ClusterRole

Error: 1 chart(s) linted, 1 chart(s) failed
```

**Which issue(s) this PR fixes**:

No known bug exists.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Comment by gazal-k** [comment]
could a maintainer please prepare a new release with this change soon?

**Comment by andyzhangx** [comment]
v4.1.0 should have the right format now

**Comment by gazal-k** [comment]
> v4.1.0 should have the right format now

That was quick. Thank you 🙂

**Pull request merged**
