### PR TITLE
Added missing curly brace.

### PR DESCRIPTION
**Pull request by GarbageYard**
**What type of PR is this?**
/kind bug
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Seems a curly brace went missing 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note
none
```

### CODE REVIEW

**Review by wozniakjan — COMMENTED** [review]
/ok-to-test
/lgtm
Thank you!

**Comment by GarbageYard** [comment]
> @GarbageYard pls sign the cla first? thanks.

@andyzhangx : I have signed it now. Thank you.

**Comment by gclawes** [comment]
Why is this changing an existing version in-place?

**Comment by endriu0** [comment]
@GarbageYard  you'll need to run below to get tests passing :

helm package charts/latest/csi-driver-nfs -d charts/latest/
helm package charts/v4.4.0/csi-driver-nfs -d charts/v4.4.0/

**Pull request closed without merging**
