### PR TITLE
Windows go version

### PR DESCRIPTION
**Pull request by pierreprinetti**
/kind failing-test

**What this PR does / why we need it**:
Prior to this patch, the Go version for the Windows tests in Github
resolved to [`1.15.15`][1].

With this patch, the Go version for the Windows tests is fixed to
actually resolve to the latest version (^1.16), consistent to the other
platforms.

This patch also bumps [`actions/setup-go`][2] to the latest version,
consistent with the other platforms.

Lastly, in order to rapidly debug test issues, issue `go version` prior to
running any test.

[1]: https://github.com/kubernetes-csi/csi-driver-nfs/runs/4211323920?check_suite_focus=true
[2]: https://github.com/actions/setup-go

**Does this PR introduce a user-facing change?**:
```release-note
none
```

### CODE REVIEW

**Comment by pierreprinetti** [comment]
> go version go1.15.15 windows/amd64

Still perfectible

**Comment by pierreprinetti** [comment]
This is good to go! All platforms now consistently run `1.17.3`.

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
