### PR TITLE
doc: comment mount-options in example

### LINKED ISSUE #274: hack/verify-examples.sh fails with 'secrets "mount-options" not found' error
**What happened**:

Installed NFS CSI driver v3.1.0 according to https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/docs/install-csi-driver-v3.1.0.md 
```
$ git clone https://github.com/kubernetes-csi/csi-driver-nfs.git
$ cd csi-driver-nfs
$  ./deploy/install-driver.sh v3.1.0 local
```

then ran bellow:
```
$ ./hack/verify-examples.sh 
```

failed to create deployment `deployment-nfs` and pvc `pvc-deployment-nfs` .

```
$ kubectl describe pvc pvc-deployment-nfs
...
Events:
  Type     Reason                Age                    From                                                             Message
  ----     ------                ----                   ----                                                             -------
  Warning  ProvisioningFailed    12m (x14 over 33m)     nfs.csi.k8s.io_kind-worker_362e77fe-f5a2-427b-93f4-066d70f61dbe  failed to provision volume with StorageClass "nfs-csi": error getting secret mount-options in namespace default: secrets "mount-options" not found
  Normal   ExternalProvisioning  3m30s (x122 over 33m)  persistentvolume-controller                                      waiting for a volume to be created, either by external provisioner "nfs.csi.k8s.io" or manually created by system administrator
  Normal   Provisioning          7s (x17 over 33m)      nfs.csi.k8s.io_kind-worker_362e77fe-f5a2-427b-93f4-066d70f61dbe  External provisioner is provisioning volume for claim "default/pvc-deployment-nfs" 
```

**What you expected to happen**:

pvc and deployment created successfully

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: v3.1.0 
- Kubernetes version (use `kubectl version`): 
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from /etc/os-release): Ubuntu 18.04.5 LTS
- Kernel (e.g. `uname -a`):
- Install tools: kind
- Others:

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
 /kind documentation

**What this PR does / why we need it**:
doc: remove mount-options in example

**Which issue(s) this PR fixes**:

Fixes #274

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Comment by pohly** [comment]
Why this change?

I have no opinion about it. But as I don't see a reason in the commit message or the PR description, I can't review this.

**Comment by andyzhangx** [comment]
> Why this change?
> 
> I have no opinion about it. But as I don't see a reason in the commit message or the PR description, I can't review this.

if fixed #274, we only want to make this secret optional in storage class example, otherwise user would hit error when applying this example. I renamed this PR title to `comment mount-options in example`

**Comment by YuikoTakada** [comment]
Thank you for your PR.
Is this `/kind documentation` ? not `/kind bug` ?

**Comment by andyzhangx** [comment]
> Thank you for your PR. Is this `/kind documentation` ? not `/kind bug` ?

@YuikoTakada aha, it's doc bug

**Pull request merged**
