### PR TITLE
fix: update livenessprobe version from v1.1.0 to v2.0.0

### PR DESCRIPTION
**Pull request by jiaxunsongucb**
**What type of PR is this?**
/kind bug
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Replace livenessprobe flag --connection-timeout with --probe-timeout.
Update the livenessprobe version from v1.1.0 to v2.0.0.
Update helm charts.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by mayankshah1607** [comment]
Thanks for the PR @jiaxunsongucb ! Could you also update the manifests under the [`deploy/`](https://github.com/kubernetes-csi/csi-driver-nfs/tree/master/deploy/kubernetes) folder?
I believe [`csi-driver-smb` Helm chart](https://github.com/kubernetes-csi/csi-driver-smb/tree/master/charts) also uses `v1.1.0`. Could you make this update there as well?
Thanks :)

**Comment by jiaxunsongucb** [comment]
> Thanks for the PR @jiaxunsongucb ! Could you also update the manifests under the [`deploy/`](https://github.com/kubernetes-csi/csi-driver-nfs/tree/master/deploy/kubernetes) folder?
> I believe [`csi-driver-smb` Helm chart](https://github.com/kubernetes-csi/csi-driver-smb/tree/master/charts) also uses `v1.1.0`. Could you make this update there as well?
> Thanks :)

Manifests under `deploy/` folder are changed in this PR. I will do the change for `csi-driver-smb`. Thank you!

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
