### PR TITLE
test: add make verify

### PR DESCRIPTION
**Pull request by songjiaxun**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

/kind failing-test

**What this PR does / why we need it**:
Add make verify.
Add tear down for unit tests.
Fix hack scripts.
**NOTE**: `make verify` will fail and they are not fixed in this PR because there are too many issues. I will address these issues in another PR.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by msau42** [comment]
It would be nice to add these verifications to https://github.com/kubernetes-csi/csi-release-tools so that we can share the same validation logic across all the csi repos.

**Comment by songjiaxun** [comment]
> It would be nice to add these verifications to https://github.com/kubernetes-csi/csi-release-tools so that we can share the same validation logic across all the csi repos.

Agree. I can do it later.

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
