### PR TITLE
update sidecars to latest version

### PR DESCRIPTION
**Pull request by humblec**
> /kind cleanup

```release-note
NONE
```

### CODE REVIEW

**Review by ggriffiths — APPROVED** [review]
/lgtm

**Comment by humblec** [comment]
@andyzhangx ptal..thanks!

**Comment by andyzhangx** [comment]
test-infra is broken now... waiting for fix

**Comment by humblec** [comment]
@andyzhangx the fix is part of `2.6.0` of n-d-r sidecar.  https://github.com/kubernetes-csi/node-driver-registrar/blob/release-2.6/CHANGELOG/CHANGELOG-2.6.md . If thats the case why its failing with those versions?

**Comment by andyzhangx** [comment]
> @andyzhangx the fix is part of `2.6.0` of n-d-r sidecar. https://github.com/kubernetes-csi/node-driver-registrar/blob/release-2.6/CHANGELOG/CHANGELOG-2.6.md . If thats the case why its failing with those versions?

@humblec I mean the fix is revert of this PR: https://github.com/kubernetes-csi/node-driver-registrar/pull/247, v2.6.0 & v2.6.1 is actually broken now.

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Comment by andyzhangx** [comment]
@humblec there is already an ask to publish a new release here: https://github.com/kubernetes-csi/node-driver-registrar/pull/247#issuecomment-1332021520

**Pull request merged**
